import { db } from '@/db';
import { authenticationLogs } from '@/db/schema';

async function main() {
    const now = Date.now();
    
    const sampleAuthenticationLogs = [
        {
            userId: 'user_test_001',
            timestamp: now - 3600000,
            svScore: 92.5,
            cmScore: 89.3,
            fusionScore: 90.8,
            decision: 'ACCEPT',
            deviceId: 'device_chrome_mac_001',
            ipAddress: '192.168.1.105',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            audioDuration: 3.2,
            snrScore: 28.5,
            audioQuality: 'excellent',
            spoofingIndicators: null,
            failureReason: null,
            createdAt: now - 3600000,
            challengePhrase: 'My voice is my password',
            channelType: 'microphone',
            audioQualitySnr: 28.5,
            backgroundNoiseLevel: 0.15,
        },
        {
            userId: 'user_test_002',
            timestamp: now - 7200000,
            svScore: 87.2,
            cmScore: 84.6,
            fusionScore: 85.9,
            decision: 'ACCEPT',
            deviceId: 'device_firefox_win_002',
            ipAddress: '10.0.0.45',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
            audioDuration: 4.1,
            snrScore: 24.3,
            audioQuality: 'good',
            spoofingIndicators: null,
            failureReason: null,
            createdAt: now - 7200000,
            challengePhrase: 'Verify my identity with voice',
            channelType: 'webrtc',
            audioQualitySnr: 24.3,
            backgroundNoiseLevel: 0.28,
        },
        {
            userId: 'user_test_001',
            timestamp: now - 10800000,
            svScore: 94.8,
            cmScore: 91.7,
            fusionScore: 93.2,
            decision: 'ACCEPT',
            deviceId: 'device_chrome_mac_001',
            ipAddress: '192.168.1.105',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            audioDuration: 2.8,
            snrScore: 32.1,
            audioQuality: 'excellent',
            spoofingIndicators: null,
            failureReason: null,
            createdAt: now - 10800000,
            challengePhrase: 'My voice is my password',
            channelType: 'microphone',
            audioQualitySnr: 32.1,
            backgroundNoiseLevel: 0.12,
        },
        {
            userId: 'user_test_003',
            timestamp: now - 14400000,
            svScore: 48.3,
            cmScore: 52.1,
            fusionScore: 50.2,
            decision: 'REJECT',
            deviceId: 'device_safari_ios_003',
            ipAddress: '172.16.0.89',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
            audioDuration: 3.5,
            snrScore: 12.4,
            audioQuality: 'poor',
            spoofingIndicators: '{"spectral_artifacts": true, "unnatural_transitions": true}',
            failureReason: 'Speaker verification score below threshold',
            createdAt: now - 14400000,
            challengePhrase: 'Authenticate using my voice',
            channelType: 'phone',
            audioQualitySnr: 12.4,
            backgroundNoiseLevel: 0.67,
        },
        {
            userId: 'user_test_002',
            timestamp: now - 18000000,
            svScore: 89.1,
            cmScore: 87.5,
            fusionScore: 88.3,
            decision: 'ACCEPT',
            deviceId: 'device_firefox_win_002',
            ipAddress: '10.0.0.45',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
            audioDuration: 3.9,
            snrScore: 26.7,
            audioQuality: 'good',
            spoofingIndicators: null,
            failureReason: null,
            createdAt: now - 18000000,
            challengePhrase: 'Verify my identity with voice',
            channelType: 'webrtc',
            audioQualitySnr: 26.7,
            backgroundNoiseLevel: 0.23,
        },
        {
            userId: 'user_test_003',
            timestamp: now - 21600000,
            svScore: 91.6,
            cmScore: 88.9,
            fusionScore: 90.2,
            decision: 'ACCEPT',
            deviceId: 'device_safari_ios_003',
            ipAddress: '172.16.0.89',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
            audioDuration: 4.5,
            snrScore: 29.3,
            audioQuality: 'excellent',
            spoofingIndicators: null,
            failureReason: null,
            createdAt: now - 21600000,
            challengePhrase: 'My voice unlocks access',
            channelType: 'microphone',
            audioQualitySnr: 29.3,
            backgroundNoiseLevel: 0.18,
        },
        {
            userId: 'user_test_001',
            timestamp: now - 25200000,
            svScore: 73.8,
            cmScore: 76.2,
            fusionScore: 75.0,
            decision: 'FALLBACK',
            deviceId: 'device_edge_win_004',
            ipAddress: '192.168.1.120',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
            audioDuration: 5.2,
            snrScore: 18.9,
            audioQuality: 'fair',
            spoofingIndicators: '{"background_noise": true}',
            failureReason: 'Fusion score in uncertain range, requesting additional verification',
            createdAt: now - 25200000,
            challengePhrase: 'Voice authentication required',
            channelType: 'voip',
            audioQualitySnr: 18.9,
            backgroundNoiseLevel: 0.52,
        },
        {
            userId: 'user_test_002',
            timestamp: now - 28800000,
            svScore: 45.7,
            cmScore: 48.3,
            fusionScore: 47.0,
            decision: 'REJECT',
            deviceId: 'device_firefox_win_002',
            ipAddress: '10.0.0.45',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
            audioDuration: 2.9,
            snrScore: null,
            audioQuality: 'poor',
            spoofingIndicators: '{"replay_attack": true, "spectral_artifacts": true}',
            failureReason: 'Countermeasure detected possible spoofing attempt',
            createdAt: now - 28800000,
            challengePhrase: 'Verify my identity with voice',
            channelType: 'webrtc',
            audioQualitySnr: 10.2,
            backgroundNoiseLevel: 0.78,
        },
        {
            userId: 'user_test_003',
            timestamp: now - 32400000,
            svScore: 96.2,
            cmScore: 93.8,
            fusionScore: 95.0,
            decision: 'ACCEPT',
            deviceId: 'device_safari_ios_003',
            ipAddress: '172.16.0.89',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
            audioDuration: 3.7,
            snrScore: 34.6,
            audioQuality: 'excellent',
            spoofingIndicators: null,
            failureReason: null,
            createdAt: now - 32400000,
            challengePhrase: 'My voice unlocks access',
            channelType: 'microphone',
            audioQualitySnr: 34.6,
            backgroundNoiseLevel: 0.09,
        },
        {
            userId: 'user_test_001',
            timestamp: now - 36000000,
            svScore: 88.5,
            cmScore: 86.2,
            fusionScore: 87.3,
            decision: 'ACCEPT',
            deviceId: 'device_chrome_mac_001',
            ipAddress: '192.168.1.105',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            audioDuration: 4.3,
            snrScore: 27.1,
            audioQuality: 'good',
            spoofingIndicators: null,
            failureReason: null,
            createdAt: now - 36000000,
            challengePhrase: 'My voice is my password',
            channelType: 'microphone',
            audioQualitySnr: 27.1,
            backgroundNoiseLevel: 0.21,
        },
    ];

    await db.insert(authenticationLogs).values(sampleAuthenticationLogs);
    
    console.log('✅ Authentication logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});